# Generated by Django 3.0.7 on 2020-09-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformssports',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
