# Generated by Django 3.0.4 on 2020-03-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='total',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
