# Generated by Django 3.0.4 on 2020-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('confma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationclient',
            name='total',
        ),
        migrations.AddField(
            model_name='quotation',
            name='total',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='value_embroidery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='value_necks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='value_prints',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
