# Generated by Django 3.0.4 on 2020-03-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0002_quotation_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total',
        ),
    ]
