# Generated by Django 3.0.4 on 2020-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('confma', '0002_auto_20200430_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2,
                                      default=0, max_digits=9,
                                      null=True),
        ),
    ]
