# Generated by Django 3.0.7 on 2020-09-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0002_uniformssports_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantsmale',
            name='ref',
            field=models.CharField(default='ref', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shirtsmale',
            name='ref',
            field=models.CharField(default='ref', max_length=10, null=True),
        ),
    ]
