# Generated by Django 3.0.7 on 2020-10-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0003_auto_20201005_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformsfemale',
            name='pants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confma.Pants'),
        ),
        migrations.AlterField(
            model_name='uniformsfemale',
            name='dress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confma.DressesUniform'),
        ),
        migrations.AlterField(
            model_name='uniformsfemale',
            name='shirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confma.Shirts'),
        ),
    ]
