# Generated by Django 3.0.7 on 2020-10-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0003_auto_20200929_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformsmale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
