# Generated by Django 3.0.7 on 2020-10-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0004_auto_20201006_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformsfemale',
            name='pants',
        ),
    ]
