# Generated by Django 3.0.7 on 2020-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0004_uniforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniforms',
            name='fashion',
        ),
        migrations.AddField(
            model_name='uniforms',
            name='type_uniform',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=1, max_length=10),
        ),
    ]
