# Generated by Django 3.0.7 on 2020-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0005_auto_20200909_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformsFemale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_college', models.CharField(max_length=100)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UniformsFemale',
            },
        ),
        migrations.CreateModel(
            name='UniformsMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_college', models.CharField(max_length=100)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UniformsMale',
            },
        ),
    ]
