# Generated by Django 3.0.7 on 2020-10-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0006_auto_20201009_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pants',
            name='type',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('SportMale', 'SportMale'), ('SportFemale', 'SportFemale')], default=1, max_length=20, null=True),
        ),
    ]
