# Generated by Django 3.0.7 on 2020-09-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0007_auto_20200909_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_college', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Shields',
            },
        ),
        migrations.AddField(
            model_name='uniformsfemale',
            name='dress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confma.DressesUniform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformsfemale',
            name='shirt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confma.ShirtsUniformFemale'),
            preserve_default=False,
        ),
    ]
