# Generated by Django 3.0.7 on 2020-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0008_auto_20200910_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressesuniform',
            name='image',
            field=models.ImageField(null=True, upload_to='uniforms/Female/dresses/%Y/%m/%d/'),
        ),
    ]
