# Generated by Django 3.0.7 on 2020-09-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confma', '0010_auto_20200910_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantsMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=1, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='uniforms/Male/pants/%Y/%m/%d/')),
                ('state', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PantsUniformMale',
            },
        ),
        migrations.RenameModel(
            old_name='ShirtsUniformFemale',
            new_name='ShirtsFemale',
        ),
        migrations.DeleteModel(
            name='PantsUniformMale',
        ),
        migrations.AddField(
            model_name='uniformsmale',
            name='shirt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confma.ShirtsUniformMale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformsmale',
            name='pants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confma.PantsMale'),
            preserve_default=False,
        ),
    ]
